delete_not_authorized_users:
  cron: "1 4 * * 1"
  class: "CronUserDeleteJob"
  queue: default

parsing:
  cron: "0 0 * * 3 *"
  class: "ParsingJob"
  queue: default

parser:
  cron: "1 4 1 * *"
  class: "ParserJob"
  queue: default
